name: Docker Image CI Backend Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: kennethfoo49066         # your Docker Hub user/org
      IMAGE_NAME: all-language-elastic-golang             # image name for the Go service

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'               
        cache: true                       # speeds up repeated builds

    #Build & push the Docker image
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}
        registry: docker.io
        dockerfile: golang/Dockerfile         # change if your Dockerfile is elsewhere
        tags: ${{ github.sha }},latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
